services:
  library:
    image: node:18
    container_name: library
    build:
      context: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PORT=3095
    ports:
      - 3095:3095
    command: sh -c "yarn && yarn server"
    networks:
      - network
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - network
networks:
  network: 
    driver: bridge
